[build]
  command = "npm run build"  # あなたのビルドコマンドに置き換えてください
  publish = "build"  # ビルド出力ディレクトリ、create-react-appの場合は通常 "build"
  functions = "netlify/functions"  # サーバーレス関数のディレクトリ

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["replicate"]

[functions."replicateProxy"]
  included_files = ["node_modules/replicate/**"]
  timeout = "100000" 